import { useEffect, useState } from 'react';
import {
  Box, Button, Typography, TextField, IconButton, InputAdornment, Paper,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow,
  Menu, MenuItem, Checkbox, Avatar, InputBase, Tabs, Tab, Breadcrumbs
} from '@mui/material';
import { useNavigate } from "react-router-dom";
import MoreVertIcon from '@mui/icons-material/MoreVert';
import SearchIcon from '@mui/icons-material/Search';
import Sidebar from './Sidebar';
import ArrowDropDownIcon from '@mui/icons-material/ArrowDropDown';
import NotificationsNoneIcon from '@mui/icons-material/NotificationsNone';
import axios from 'axios';

const PurchaseOrderActions = () => {
  const navigate = useNavigate();
  const [anchorEl, setAnchorEl] = useState(null);
  const [menuIndex, setMenuIndex] = useState(null);
  const [tab, setTab] = useState(0);
  const [rows, setRows] = useState([]);

  useEffect(() => {
    axios.get('http://localhost:5000/api/purchase')
        .then(res => {
            // Group by purchase_order_no so each order appears only once
            const grouped = {};
            res.data.forEach(row => {
                if (!grouped[row.purchase_order_no]) {
                    grouped[row.purchase_order_no] = row;
                }
            });
            setRows(Object.values(grouped));
        })
        .catch(() => setRows([]));
  }, []);

  const filteredRows = rows.filter(row => {
    if (tab === 0) return true;
    if (tab === 1) return row.status === 'Sent';
    if (tab === 2) return row.status === 'Draft';
    return true;
  });

  const handleMenuOpen = (event, index) => {
    setAnchorEl(event.currentTarget);
    setMenuIndex(index);
  };

  const handleMenuClose = () => {
    setAnchorEl(null);
    setMenuIndex(null);
  };
  const handleEditPurchase = (id) => {
    navigate(`/edit-purchase/${id}`);
  };

  const handleDownloadPdf = (order) => {
    import('jspdf').then(({ jsPDF }) => {
      const doc = new jsPDF();
      doc.setFontSize(18);
      doc.text("Purchase Order Document", 105, 20, null, null, "center");
      doc.line(20, 25, 190, 25);
      let y = 40;
      const details = [
        ['Order #', order.orderNo],
        ['Vendor', order.vendor],
        ['Created Date', order.created],
        ['Delivery Date', order.delivery],
        ['Status', order.status],
        ['Amount', order.amount]
      ];
      details.forEach(([label, value]) => {
        doc.setFont("helvetica", "bold");
        doc.text(`${label}:`, 25, y);
        doc.setFont("helvetica", "normal");
        doc.text(`${value}`, 70, y);
        y += 12;
      });
      doc.save(`${order.orderNo}.pdf`);
    });
  };

  const handlePrintOrder = (order) => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html><head><title>Print Purchase Order</title>
      <style>body{font-family:Arial;margin:40px;}h1{text-align:center;color:#003366;}p{font-size:16px;}</style>
      </head><body>
      <h1>Purchase Order Document</h1>
      <p><b>Order #:</b> ${order.orderNo}</p>
      <p><b>Vendor:</b> ${order.vendor}</p>
      <p><b>Created Date:</b> ${order.created}</p>
      <p><b>Delivery Date:</b> ${order.delivery}</p>
      <p><b>Status:</b> ${order.status}</p>
      <p><b>Amount:</b> ${order.amount}</p>
      <p style="margin-top:40px;font-style:italic;text-align:center;">Generated by ERP Software</p>
      </body></html>`);
    printWindow.document.close();
    printWindow.print();
  };

  const handleSendEmail = (order) => {
    const subject = encodeURIComponent(`Purchase Order ${order.orderNo}`);
    const body = encodeURIComponent(`Hi,\n\nHere are your purchase order details:\nOrder #: ${order.orderNo}\nVendor: ${order.vendor}\nAmount: ${order.amount}\nDelivery Date: ${order.delivery}`);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const handleShareLink = (order) => {
    navigator.clipboard.writeText(`https://dummy-purchase-order-link/${order.orderNo}`);
    alert('Purchase order link copied to clipboard!');
  };

  return (
    <Box display="flex">
      <Sidebar />
      <Box flex={1} display="flex" flexDirection="column" minHeight="100vh">
        <Box display="flex" justifyContent="space-between" alignItems="center" p={2}>
          <Breadcrumbs><Typography color="text.primary">Purchase Order</Typography></Breadcrumbs>
          <Box display="flex" gap={2}>
            <Paper elevation={0} sx={{ display: 'flex', alignItems: 'center', px: 1.5, py: 0.5, borderRadius: '999px', border: '1px solid #e0e0e0', bgcolor: '#f9fafb', width: 240 }}>
              <SearchIcon sx={{ fontSize: 20, color: '#999' }} />
              <InputBase placeholder="Search anything here..." sx={{ ml: 1, fontSize: 14, flex: 1 }} inputProps={{ 'aria-label': 'search' }} />
            </Paper>
            <IconButton sx={{ borderRadius: '12px', border: '1px solid #e0e0e0', bgcolor: '#f9fafb', p: 1 }}>
              <NotificationsNoneIcon sx={{ fontSize: 20, color: '#666' }} />
            </IconButton>
            <Box display="flex" alignItems="center" gap={1}>
              <Avatar src="https://i.pravatar.cc/40?img=1" />
              <Typography fontSize={14}>Admin name</Typography>
              <ArrowDropDownIcon />
            </Box>
          </Box>
        </Box>

        <Box p={3}>
          <Paper sx={{ p: 1, borderRadius: 2 }}>
            <Box display="flex" justifyContent="space-between" alignItems="center" px={4} py={2} borderBottom="1px solid #e0e0e0">
              <Typography fontWeight="bold" fontSize={18}>Purchase Order</Typography>
              <Button variant="contained" onClick={()=>
window.location.href = '/add-purchase-order'
              } sx={{ textTransform: 'none', borderRadius: 2, bgcolor: '#004085', color: '#fff', '&:hover': { bgcolor: '#003366' } }}>+ New Purchase Order</Button>
            </Box>
            <Box px={4} pt={2} display="flex" justifyContent="space-between" alignItems="center">
              <Tabs value={tab} onChange={(e, newTab) => setTab(newTab)} sx={{ '& .MuiTab-root': { textTransform: 'none', bgcolor: '#f1f1f1', borderRadius: 2, mr: 1 }, '& .Mui-selected': { bgcolor: '#004085', color: 'white !important' }, '& .MuiTabs-indicator': { display: 'none' } }}>
                <Tab label="All Purchase Order" />
                <Tab label="Sent Purchase Order" />
                <Tab label="Draft Purchase Order" />
              </Tabs>
              <TextField size="small" placeholder="Search by item name..." InputProps={{ startAdornment: (<InputAdornment position="start"><SearchIcon /></InputAdornment>), sx: { bgcolor: 'white', borderRadius: 2 } }} />
            </Box>

            <TableContainer component={Paper} sx={{ boxShadow: 'none', mt: 2 }}>
              <Table size="small">
                <TableHead sx={{ backgroundColor: '#F9FAFB' }}>
                  <TableRow>
                    <TableCell><Checkbox /></TableCell>
                    <TableCell>Purchase Order #</TableCell>
                    <TableCell>Vendor Name</TableCell>
                    <TableCell>Created Date</TableCell>
                    <TableCell>Delivery Date</TableCell>
                    <TableCell>Status</TableCell>
                    <TableCell>Bill Amount</TableCell>
                    <TableCell>Action</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {filteredRows.map((row, i) => (
                    <TableRow key={i}>
                      <TableCell><Checkbox /></TableCell>
                      <TableCell sx={{ color: '#0B5FFF', fontWeight: 500 }}>{row.purchase_order_no}</TableCell>
                      <TableCell>{row.vendor_name}</TableCell>
                      <TableCell>{row.purchase_order_date ? row.purchase_order_date.slice(0,10) : ''}</TableCell>
                      <TableCell>{row.delivery_date ? row.delivery_date.slice(0,10) : ''}</TableCell>
                      <TableCell>
                        <Typography variant="caption" sx={{ backgroundColor: '#F2F4F7', color: '#344054', px: 1.5, py: 0.5, borderRadius: '12px', fontWeight: 600 }}>Draft</Typography>
                      </TableCell>
                      <TableCell>{row.total ? `₹${row.total}` : ''}</TableCell>
                      <TableCell>
                        <IconButton onClick={(e) => handleMenuOpen(e, i)}><MoreVertIcon /></IconButton>
                        <Menu anchorEl={anchorEl} open={Boolean(anchorEl) && menuIndex === i} onClose={handleMenuClose}>
                          <MenuItem onClick={() => handleEditPurchase(row._id)}>Edit</MenuItem>
                          <MenuItem onClick={() => handleDownloadPdf(row)}>Download PDF</MenuItem>
                          <MenuItem onClick={() => handlePrintOrder(row)}>Print</MenuItem>
                          <MenuItem onClick={() => handleSendEmail(row)}>Send Email</MenuItem>
                          <MenuItem onClick={() => handleShareLink(row)}>Share Link</MenuItem>
                        </Menu>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
            <Box display="flex" justifyContent="space-between" alignItems="center" mt={2}>
              <Typography variant="body2">Showing 1 to 10 of 10 entries</Typography>
              <Box display="flex" gap={1}>
                {[1, 2, 3].map(page => (
                  <Button key={page} size="small" variant={page === 1 ? 'outlined' : 'text'}>{page}</Button>
                ))}
              </Box>
            </Box>
          </Paper>
        </Box>
      </Box>
    </Box>
  );
};

export default PurchaseOrderActions;
